name: Integration Test (latest)

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - release-please--branches--main

jobs:
  backend:
    strategy:
      fail-fast: false
      matrix:
        component: 
          [
            model-backend, 
            controller-model
          ]
    uses: instill-ai/model/.github/workflows/integration-test-backend.yml@ins-1105-fix-the-the-integration-test-cicd-in-all-projects  
    with:
      component: ${{ matrix.component }}
      target: latest
  # console:
  #   uses: instill-ai/model/.github/workflows/integration-test-console.yml@ins-1105-fix-the-the-integration-test-cicd-in-all-projects  
  #   with:
  #     target: latest
