name: Integration Test (release)

on:
  workflow_dispatch:
  push:
    branches:
      - release-please--branches--main

jobs:
  backend:
    strategy:
      fail-fast: false
      matrix:
        component: [model-backend, controller-model]
    uses: instill-ai/model/.github/workflows/integration-test-backend.yml@ins-1105-fix-the-the-integration-test-cicd-in-all-projects  
    with:
      component: ${{ matrix.component }}
      target: release
  # console:
  #   uses: instill-ai/model/.github/workflows/integration-test-console.yml@ins-1105-fix-the-the-integration-test-cicd-in-all-projects  
  #   with:
  #     target: release
